@startuml
cloud ip_offices
cloud AWS_s3 {
folder ipaustralia.marqstat.raw {
folder au
folder ca
folder ch
folder em
folder nz
folder sg
folder uk
folder us
}
folder ipaustralia.marqstat.parquets {
[au ]
[ca ]
[ch ]
[em ]
[nz ]
[sg ]
[uk ]
[us ]
}
}
control source
control conversion
control transformation
control tmlink
control marqstat
database POSTGRES.MARQSTAT

ip_offices -> source: get_office_data(xml,api,csv)
source -> ipaustralia.marqstat.raw
AWS_s3 -> conversion: raw_to_parquet(raw)
conversion -> ipaustralia.marqstat.parquets
AWS_s3 -> transformation
transformation -> POSTGRES.MARQSTAT: build_marqstat(parquets)
POSTGRES.MARQSTAT -> tmlink: links_trademarks() return parquet[county,applicant,uid_trademark]
tmlink -> POSTGRES.MARQSTAT: write_link_table()

@enduml


cloud "IP office Data" {

}

ip_office_data ->  S3_bulk_storage: get_office_data():
S3_bulk_storage -> MARQSTAT_raw: populate_MARQSTAT_raw()

 poplate_MARQSTAT_raw -> raw_storage


MARQSTAT_raw -> build_MARQSTAT: de
cloud {
  [Example 1]
  [Example 2]
}
build_MARQSTAT -> TMLINK: linktrademarks
build_MARQSTAT -> MARQSTAT: populate_MARQSTAT
MARQSTAT_raw -> TMLINK

control populate_MARQSTAT_raw
entity S3_bulk_storage
control poplate_MARQSTAT_raw

control build_MARQSTAT
control TMLINK
actor data_tech
database MARQSTAT
